### ISSUE TITLE
test pub is actually a dev dependency

### ISSUE THREAD

**Issue by MBulli** [egyleader/countries_utils#3]
`test` pub should be under `dev_dependencies:` in the pubspec.yaml file.
See https://dart.dev/tools/pub/dependencies#dev-dependencies

Right now `test` is drawn as a dependency into my app and causes version mismatches from time to time.

**Comment by egyleader** [comment]
solved , please update to version `countries_utils: 1.0.1` or later

**Comment by MBulli** [comment]
Thanks!
